name: Java CI with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./Trees/gradlew

    - name: Grant execute permission for test script
      run: chmod +x ./Trees/run_task4_tests.sh

    - name: Build & test
      working-directory: ./task4
      run: ./run_task4_tests.sh
