name: CI for Task 4

on:
  push:
    paths:
      - 'trees/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Set up JDK'
        uses: 'actions/setup-java@v4'
        with:
          java-version: '20'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./trees/gradlew

      - name: Grant execute permission for test script
        run: chmod +x ./trees/run_trees_tests.sh

      - name: Build & test
        working-directory: ./trees
        run: ./run_trees_tests.sh
